# Default pre-commit configuration for mkplaylist
# This configuration only checks code without making changes

repos:
  # Branch protection hook - runs first to fail fast
  - repo: local
    hooks:
      - id: no-commit-to-master
        name: Prevent commits to master/main branch
        entry: scripts/no-commit-to-master.sh
        language: script
        pass_filenames: false
        # This hook runs regardless of which files are being committed
        # It checks the current branch name and blocks commits to master/main

      - id: check-files
        name: Check for trailing whitespace and missing newlines
        entry: scripts/check-files.sh
        language: script
        pass_filenames: false
        # This hook checks all files for trailing whitespace and missing newlines

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-case-conflict

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: []
        # Use the project's .flake8 configuration

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--check, --jobs=-1]
        # Only check, don't modify, use all cpus

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [--diff, --recursive, --exclude=venv/*]
        # Only check, don't modify
        # Uses the project's .style.yapf configuration

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-setuptools
        # Only check, don't modify
        args: [--no-strict-optional, --ignore-missing-imports]
        
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args: [--title, "## Table of Contents", --maxlevel, "4"]
        # This will check if the TOC is up to date, but won't modify files

# Configuration is compatible with existing .flake8 and .style.yapf files
# This configuration only performs checks and does not modify any files
